name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ⚙️ Install composer
        uses: php-actions/composer@v5
      - name: 🧪 Run Tests
        run: ./vendor/bin/phpunit -vvv
